services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
      args:
        - USER_ID
        - USER_GROUP_ID
        - EXTERNAL_HOST
        - EXTERNAL_NGINX_PORT
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${EXTERNAL_NGINX_PORT}:80
    depends_on:
      - php-fpm
    environment:
      TZ: Europe/Moscow
    networks:
      - backend
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - sqldb
      - php-cli
    ports:
      - "9001:9001"
    environment:
      ENV: ${APP_ENV}
      TZ: Europe/Moscow
    networks:
      - backend
  php-cli:
    build:
      context: ./docker/php-cli
    user: ${USER_ID}:${USER_GROUP_ID}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ./:/var/www
      - composer:/.composer:rw
    command: [ "composer", "install", "--ignore-platform-reqs", "--no-scripts", "--prefer-dist" ]
    depends_on:
      - sqldb
    environment:
      ENV: ${APP_ENV}
      TZ: Europe/Moscow
      PHP_CS_FIXER_ALLOW_XDEBUG: 0
    networks:
      - backend
  cron:
    build:
      context: ./docker/php-cron
    volumes:
      - ./:/var/www
    depends_on:
      - php-cli
    command: ["cron","-f", "-l", "2", "-L", "/dev/stdout"]
    environment:
      ENV: ${APP_ENV}
    networks:
      - backend
  sqldb:
    image: mysql:5.7
    volumes:
      - sql_data:/var/lib/mysql:z
    ports:
      - ${EXTERNAL_SQLDB_PORT}:3306
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: ${SQL_DB_ROOT_PASSWORD}
      MYSQL_USER: ${SQL_DB_USERNAME}
      MYSQL_PASSWORD: ${SQL_DB_PASSWORD}
      MYSQL_DATABASE: ${SQL_DB_NAME}
    networks:
      - backend
  redis:
    image: redis:alpine3.22
    volumes:
      - redis_data:/data
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  sql_data:
  redis_data:
  composer:
